server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  #--------------------------charset--------------------------
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  mvc:
    static-path-pattern: /**
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    suffix: .ftl
    ftemplateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    expose-spring-macro-helpers: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/supermarket?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root123
mybatis:
  mapper-locations: classpath:mapper/*.xml
  mapUnderscoreToCamelCase: true

